// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Bhomes_ERP.Models.VM_Model;

public partial class VM_Designation
{
    public int DesigId { get; set; }

    [Required]
    public string DesignationTitle { get; set; }

    public int? DesignationLevel { get; set; }

    [Required]
    public string Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? EditDate { get; set; }

    public DateTime? CreatedBy { get; set; }

    public DateTime? EditedBy { get; set; }
}