// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Bhomes_ERP.Models.VM_Model;

public partial class VM_EmployeeType
{
    public int EmpTypeId { get; set; }

    [Required]
    public string EmployeeType { get; set; }

    public int? CompanyId { get; set; }

    public string Status { get; set; }

    public string CreateUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public string EditUserId { get; set; }

    public DateTime? EditDate { get; set; }
}