// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bhomes_ERP.Models.VM_Model;

public partial class VM_EmpEducationType
{
    public int EmpEduTypeId { get; set; }

    public string EducationType { get; set; }

    public string Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? EditDate { get; set; }

    public string CreatedBy { get; set; }

    public string EditedBy { get; set; }
}