// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bhomes_ERP.Models.VM_Model;

public partial class VM_SalaryMatrix
{
    public int SalaryMatrixId { get; set; }

    public decimal BasicPercent { get; set; }

    public decimal HouseRentPercent { get; set; }

    public decimal MedicalAllowPercent { get; set; }

    public decimal ConveyanceAllowPercent { get; set; }

    public decimal EntertainAllowPercent { get; set; }

    public decimal FoodAllowPercent { get; set; }

    public decimal OwnerContributionPercent { get; set; }

    public decimal PfemployeePercent { get; set; }

    public decimal StampDeduction { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? EditDate { get; set; }

    public string CreatedBy { get; set; }

    public string EditedBy { get; set; }
}