// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bhomes_ERP.Models.VM_Model;

public partial class VM_Shift
{
    public int ShiftID { get; set; }

    public string ShiftName { get; set; }

    public string Weekend1 { get; set; }

    public string Weekend2 { get; set; }

    public TimeSpan StartTime { get; set; }

    public TimeSpan EndTime { get; set; }

    public TimeSpan? LateAllowed { get; set; }

    public string Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? EditDate { get; set; }

    public string CreatedBy { get; set; }

    public string EditedBy { get; set; }
}